// Copyright 2024 Aiuta USA, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SWIFT_PACKAGE
import AiutaCore
#endif
import Foundation

extension Aiuta {
    /// Represents the analytics configuration for the Aiuta SDK.
    /// https://docs.aiuta.com/sdk/developer/configuration/analytics/
    ///
    /// The `Analytics` struct defines how analytics events are handled within the SDK.
    /// Provide an instance with a custom `Handler` to process analytics events,
    /// or set the `analytics` property to `nil` in the configuration to disable tracking.
    public struct Analytics: Sendable {
        /// An object conforming to the `Handler` protocol that processes
        /// analytics events generated by the SDK.
        public let handler: Handler

        /// Creates an analytics configuration with a custom handler.
        ///
        /// - Parameter handler: An object conforming to the `Handler` protocol that processes
        ///   analytics events generated by the SDK.
        public init(handler: Handler) {
            self.handler = handler
        }
    }
}

extension Aiuta.Analytics {
    /// Protocol defining the requirements for an SDK analytics event handler.
    public protocol Handler: Sendable {
        /// Called when an analytics event occurs.
        ///
        /// This method is invoked by the SDK whenever an analytics event is generated.
        /// The implementation should handle the event appropriately, such as by sending
        /// it to an external analytics service or logging it for debugging purposes.
        ///
        /// - Parameter event: An `Aiuta.Event` enum representing the analytics event
        ///   that occurred, it defines various categories of events, each associated
        ///   with specific actions or states in the SDK.
        @available(iOS 13.0.0, *)
        func onAnalyticsEvent(_ event: Aiuta.Event) async
    }
}
