// Copyright 2024 Aiuta USA, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import AiutaCore

extension Aiuta {
    /// Represents an image that has been generated by the Aiuta system.
    /// This subclass includes additional properties specific to generated images,
    /// such as the IDs of the products associated with the image.
    public class GeneratedImage: Aiuta.UserImage {
        enum CodingKeys: String, CodingKey {
            case productIds
        }

        /// A list of product identifiers that were utilized during the image generation process.
        /// Each identifier corresponds to a specific product involved in the try-on session,
        /// allowing for precise tracking and reference within the system.
        public let productIds: [String]

        /// Initializes a new `Generated` image with the specified properties.
        /// - Parameters:
        ///  - id: A unique identifier for the image.
        ///  - url: The URL where the image is located.
        ///  - ownerType: The type of the image owner.
        ///  - productIds: An array of product identifiers associated with the image.
        public init(id: String, url: String, ownerType: OwnerType, productIds: [String]) {
            self.productIds = productIds
            super.init(id: id, url: url, ownerType: ownerType)
        }

        /// Initializes a `Generated` image from another `Aiuta.Image` instance,
        /// while also specifying the product IDs associated with the image.
        public init(image other: Aiuta.UserImage, productIds: [String]) {
            self.productIds = productIds
            super.init(id: other.id, url: other.url, ownerType: other.ownerType)
        }

        /// Initializes a `Generated` image from a decoder, extracting the necessary
        /// properties from the provided decoder.
        public required init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let productIds = try? container.decode([String].self, forKey: .productIds)
            self.productIds = productIds ?? []
            try super.init(from: decoder)
        }

        /// Encodes the `Generated` image properties into the provided encoder.
        override public func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(productIds, forKey: .productIds)
        }
    }
}
