// Copyright 2024 Aiuta USA, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SWIFT_PACKAGE
import AiutaCore
#endif

extension Aiuta.UserImage {
    /// Owner type primarily determines the source of origin of the image —
    /// whether it was generated by the user as a result of any chain of
    /// operations from upload to generation, possibly including re-generation.
    /// Alternatively, the image is not associated with the user's personal
    /// data and does not belong to them. This allows different approaches
    /// to be taken when deleting images from the history.
    public enum OwnerType: String, Codable {
        /// Image uploaded or generated by the user (using a camera or from a gallery).
        ///
        /// - Note: This image belongs to the user. When the user removes the image
        /// from the history, it may be deleted from the storage as well.
        case user

        /// Image of the model provided or generated by the Aiuta.
        ///
        /// - Note: This image could be linked to the user history, but it is not
        /// owned by the user, and can not be deleted from the storage, only
        /// unlinked from the user's history in case of removing.
        case aiuta
    }
}
