// Copyright 2024 Aiuta USA, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import AiutaCore

extension Aiuta {
    /// Represents an UGC image used within the SDK. Each image has a unique
    /// identifier, a URL pointing to its location, and a type that describes
    /// its purpose or ownership.
    public class UserImage: Codable {
        /// A unique string identifier assigned to the image by the Aiuta API,
        /// ensuring each image can be distinctly recognized and referenced
        /// within the system.
        public let id: String

        /// The URL pointing to the location of the image resource, which
        /// can be accessed and retrieved by the SDK to present in the UI.
        public let url: String

        /// The type of the image owner indicating whether the image was
        /// generated by the user or provided by Aiuta.
        public let ownerType: OwnerType

        /// Initializes a new `Image` instance with the specified properties.
        ///
        /// - Parameters:
        ///   - id: A unique identifier for the image.
        ///   - url: The URL where the image is located.
        ///   - ownerType: The type of the image owner.
        public init(id: String, url: String, ownerType: OwnerType) {
            self.id = id
            self.url = url
            self.ownerType = ownerType
        }

        /// Initializes a new `Image` instance from a decoder, extracting the necessary
        /// properties from the provided decoder.
        public required init(from decoder: any Decoder) throws {
            let container: KeyedDecodingContainer<Aiuta.UserImage.CodingKeys> = try decoder.container(keyedBy: Aiuta.UserImage.CodingKeys.self)
            id = try container.decode(String.self, forKey: Aiuta.UserImage.CodingKeys.id)
            url = try container.decode(String.self, forKey: Aiuta.UserImage.CodingKeys.url)
            let ownerType = try? container.decode(Aiuta.UserImage.OwnerType.self, forKey: Aiuta.UserImage.CodingKeys.ownerType)
            self.ownerType = ownerType ?? .user
        }
    }
}

extension Aiuta.UserImage: Equatable {
    /// Compares two `Image` instances to determine if they are equal. Equality
    /// is based on the unique identifier of the image.
    public static func == (lhs: Aiuta.UserImage, rhs: Aiuta.UserImage) -> Bool {
        lhs.id == rhs.id
    }
}

extension Aiuta.UserImage: Hashable {
    /// Generates a hash value for the `Image` instance. The hash is based on
    /// the unique identifier of the image.
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}
