// Copyright 2024 Aiuta USA, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/***
 '@autoclosure' must not be used on variadic parameters thats why...
 I'd like to say it's autogenerated, but no, it's a dirty copypaste.
 */

// MARK: - Simple wrappers

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2(), a3()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2(), a3(), a4()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2(), a3(), a4(), a5()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               _ a7: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6(), a7()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               _ a7: @autoclosure () -> Any?,
                               _ a8: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6(), a7(), a8()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(_ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               _ a7: @autoclosure () -> Any?,
                               _ a8: @autoclosure () -> Any?,
                               _ a9: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: " ", anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6(), a7(), a8(), a9()], file: file, line: line, function: function)
}

// MARK: - Symbolic wrappers

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2(), a3()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2(), a3(), a4()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2(), a3(), a4(), a5()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               _ a7: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6(), a7()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               _ a7: @autoclosure () -> Any?,
                               _ a8: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6(), a7(), a8()], file: file, line: line, function: function)
}

@_spi(Aiuta) public func trace(i: String,
                               _ a0: @autoclosure () -> Any?,
                               _ a1: @autoclosure () -> Any?,
                               _ a2: @autoclosure () -> Any?,
                               _ a3: @autoclosure () -> Any?,
                               _ a4: @autoclosure () -> Any?,
                               _ a5: @autoclosure () -> Any?,
                               _ a6: @autoclosure () -> Any?,
                               _ a7: @autoclosure () -> Any?,
                               _ a8: @autoclosure () -> Any?,
                               _ a9: @autoclosure () -> Any?,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    trace(statusSymbol: i, anything: [a0(), a1(), a2(), a3(), a4(), a5(), a6(), a7(), a8(), a9()], file: file, line: line, function: function)
}

// MARK: - Implementations

@_spi(Aiuta) public func trace(measure work: () -> Void,
                               file: String = #file, line: Int = #line, function: String = #function) {
    guard #available(iOS 16.0, *), isTraceEnabled else {
        work()
        return
    }
    let clock = ContinuousClock()
    let result = clock.measure(work)
    trace(statusSymbol: " ", anything: [result], file: file, line: line, function: function)
}

private func trace(statusSymbol: String, anything: [Any?], file: String, line: Int, function: String) {
    guard isTraceEnabled else { return }
    let fileName = (file as NSString).lastPathComponent
    let funcName = String(function.split(separator: "(").first ?? "func")
    let logLine = "\(fileName):\(line) .\(funcName)".padding(toLength: 50, withPad: " ", startingAt: 0) +
        "  | \(" \(statusSymbol)  |") " + anything.map { any in String(describing: any ?? "<nil>") }.joined(separator: " ")

    print(Thread.isMainThread ? "🔲" : "🧵", " | ", Date().timeIntervalSince1970.format("HH:mm:ss.SSS"), " | ", logLine)
}

@_spi(Aiuta) public func trace_call(_ fromFile: String, _ fromLine: Int, _ fromFunction: String,
                                    file: String = #file, line: Int = #line, function: String = #function) {
    guard isTraceEnabled else { return }
    let fromFileName = (fromFile as NSString).lastPathComponent
    let fileName = (file as NSString).lastPathComponent
    let fromFuncName = String(fromFunction.split(separator: "(").first ?? "fromFunc")
    let funcName = String(function.split(separator: "(").first ?? "func")
    print(
        Date().timeIntervalSince1970.format("HH:mm:ss.SSS"),
        " | ", "\(fromFileName):\(fromLine) .\(fromFuncName)".padding(toLength: 49, withPad: " ", startingAt: 0),
        " -> ", "\(fileName):\(line) .\(funcName)"
    )
}

// MARK: - Global state

@_spi(Aiuta) public func trace(isEnabled: Bool) {
    isTraceEnabled = isEnabled
}

private var isTraceEnabled = true
