// Copyright 2024 Aiuta USA, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// # Aiuta SDK Core
///
/// The foundational layer of the **Aiuta SDK**.
///
/// This module defines low-level abstractions and shared data structures used by
/// higher-level Aiuta SDK packages.
///
/// - [Aiuta Developer Documentation](https://docs.aiuta.com/)
/// - [iOS SDK documentation](https://docs.aiuta.com/sdk/ios/)
/// - [Aiuta SDK on GitHub](https://github.com/aiuta-com/aiuta-ios-sdk)
///
/// ## Overview
///
/// Aiuta enum is used as a public namespace & entry point.
///
/// ### Configuration
///
/// ``Aiuta.Configuration``
///     The configuration is structured as a hierarchical object that controls various
///     aspects of the SDK's behavior, appearance, and functionality.
///     https://docs.aiuta.com/sdk/developer/configuration/
///
///  ``Aiuta.Auth``
///     Auth is used to authenticate requests from Aiuta SDK to API with your credentials.
///     https://docs.aiuta.com/sdk/developer/configuration/auth/
///
///  ``Aiuta.Analytics``
///     Allows handle analytics events generated by the SDK.
///     By implementing the `onAnalyticsEvent` callback you can receive ``Aiuta.Event``
///     https://docs.aiuta.com/sdk/developer/configuration/analytics/
///
/// ### Types
///
/// ``Aiuta.Product``
///     Defines properties of products within the Aiuta platform for displaying product
///     information in the SDK's user interface and managing product-related functionality.
///     https://docs.aiuta.com/sdk/developer/product/
///
/// - Author: [Aiuta Team](https://aiuta.com)
public enum Aiuta {
    /// Marker class used to locate the correct bundle for the Aiuta SDK.
    private final class _BundleMarker {}

    /// The semantic version string of the **Aiuta SDK**.
    ///
    /// This constant reflects the version of the SDK package as defined by the
    /// Swift Package Manager or build system.
    ///
    /// When the SDK is integrated as a Swift Package dependency, this value is
    /// automatically populated from the Git tag used to resolve the package
    /// (for example, `"1.2.3"`).
    /// If the package is built from a local path or an untagged branch, the value
    /// falls back to `"dev"`.
    ///
    /// Use this property for:
    /// - Displaying the SDK version in diagnostic or debug information.
    /// - Reporting the SDK version in API requests or analytics events.
    /// - Verifying compatibility between Aiuta modules.
    ///
    /// ```swift
    /// print("Aiuta SDK version:", Aiuta.version)
    /// // Aiuta SDK version: 1.2.3
    /// ```
    ///
    /// - Important:
    /// This version string corresponds to the semantic version of the package,
    /// not to individual module or binary versions. All Aiuta submodules share
    /// the same semantic version number.
    ///
    /// - SeeAlso:
    /// [Semantic Versioning Specification](https://semver.org)
    public static let version: String = {
        #if SWIFTPM_PACKAGE_VERSION
            SWIFTPM_PACKAGE_VERSION
        #else
            let bundle = Bundle(for: _BundleMarker.self)
            return bundle.infoDictionary?["CFBundleShortVersionString"] as? String ?? "dev"
        #endif
    }()
}
